# Generated by Django 4.2.7 on 2023-11-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.ImageField(default=0, upload_to='books/'),
            preserve_default=False,
        ),
    ]
